apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-ds
  namespace: demo
spec:
  rules:
    - host: echo-ds.com
      http:
         paths:
           - path: /
             pathType: Prefix
             backend:
               service:
                  name: hello-ds
                  port:
                    number: 8000
